name: 05 - CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  frontend-lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd
      
      - name: Lint
        run: |
          echo "::group::Lint"
          pnpm lint:frontend

  frontend-test:
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd
      
      - name: Test
        run: |
          echo "::group::Test"
          pnpm test:frontend

  frontend-build:
      needs: [frontend-lint, frontend-test]
      runs-on: ubuntu-24.04
      steps:

      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd
      
      - name: Build
        run: |
          echo "::group::Test"
          pnpm build:frontend

  ci:
    runs-on: ubuntu-24.04
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd

      - name: Lint
        run: pnpm lint
      
      - name: Test
        run: pnpm test
      
      - name: Build
        run: pnpm build
      
  backend-lint:
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd

      - name: Lint
        run: |
          echo "::group::Lint"
          pnpm lint:backend

  backend-test:
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd

      - name: Test
        run: |
          echo "::group::Test"
          pnpm test:backend

  backend-smoke-test:
    needs: [backend-lint, backend-test]
    runs-on: ubuntu-24.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd

      - name: Smoke test
        run: |
          pnpm build:backend
          pnpm start:backend
          curl -X GET http://localhost:3000/health
          echo "::endgroup::"
          