name: 05 - CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  frontend-lint:
    runs-on: ubuntu-24.04
    steps:
      
      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd@main
      
      - name: Lint
        run: |
          echo "::group::Lint"
          pnpm lint:frontend

  frontend-test:
    runs-on: ubuntu-24.04
    steps:
      
      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd@main
      
      - name: Test
        run: |
          echo "::group::Test"
          pnpm test:frontend

  ci:
    runs-on: ubuntu-24.04
    steps:

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd@main

      - name: Lint
        run: pnpm lint
      
      - name: Test
        run: pnpm test
      
      - name: Build
        run: pnpm build
      
  backend-lint:
    runs-on: ubuntu-24.04
    steps:

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd@main

      - name: Lint
        run: |
          echo "::group::Lint"
          pnpm lint:backend

  backend-test:
    runs-on: ubuntu-24.04
    steps:

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-ci-cd@main

      - name: Test
        run: |
          echo "::group::Test"
          pnpm test:backend